<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>FROST</AssemblyName>
    <RootNamespace>FROST</RootNamespace>
    <Version>1.0.3</Version>
    <FileVersion>1.0.3.0</FileVersion>
    <AssemblyVersion>1.0.3.0</AssemblyVersion>
    <InformationalVersion>1.0.3</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Product>FROST</Product>
    <ApplicationIcon>Ressources\Icones\frost.ico</ApplicationIcon>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Ressources\Icones\frost.ico" />
    <!-- Inclut automatiquement TOUTES les images PNG (racine + sous-dossiers des thèmes) -->
    <Resource Include="Ressources\**\*.png" />
    <!-- On inclut aussi le dossier Icones s'il a été mis à la racine -->
    <Resource Include="Icones\**\*.png" />
  </ItemGroup>
</Project>
